namespace SourceGenerateHelper.Tests;

using Microsoft.CodeAnalysis;

using SourceGenerateHelper.Testing;

// Covers the additions that let a generator go from model to AddSource without hand-rolling
// the indent/newline chain, the closing-brace-with-semicolon case, or the hint name.
public sealed class SourceOutputExtensionsTest
{
    //-----------------------------------------------------------------------
    // AppendLine
    //-----------------------------------------------------------------------

    [Fact]
    public void AppendLineIndentsAndTerminates()
    {
        const string expected =
            """
            public sealed class Data
            {
                public int Id { get; set; }
            }

            """;

        var builder = new SourceBuilder();

        builder.AppendLine("public sealed class Data");
        builder.BeginScope();
        builder.AppendLine("public int Id { get; set; }");
        builder.EndScope();

        Assert.Equal(expected, builder.ToString());
    }

    //-----------------------------------------------------------------------
    // EndScope(bool)
    //-----------------------------------------------------------------------

    [Fact]
    public void EndScopeWithSemicolonClosesAnInitializer()
    {
        const string expected =
            """
            private static readonly Options Value = new()
            {
                Name = "a"
            };

            """;

        var builder = new SourceBuilder();

        builder.AppendLine("private static readonly Options Value = new()");
        builder.BeginScope();
        builder.AppendLine("Name = \"a\"");
        builder.EndScope(true);

        Assert.Equal(expected, builder.ToString());
    }

    [Fact]
    public void EndScopeWithoutSemicolonMatchesTheParameterlessOverload()
    {
        var withFlag = new SourceBuilder();
        withFlag.BeginScope();
        withFlag.EndScope(false);

        var withoutFlag = new SourceBuilder();
        withoutFlag.BeginScope();
        withoutFlag.EndScope();

        Assert.Equal(withoutFlag.ToString(), withFlag.ToString());
    }

    //-----------------------------------------------------------------------
    // SourceProductionContext.AddSource(hintName, SourceBuilder)
    //-----------------------------------------------------------------------

    [Fact]
    public void AddSourceEmitsTheBuilderUnderTheBuiltHintName()
    {
        var result = new GeneratorTestRunner(new BuilderOutputGenerator()).Run(
            """
            namespace Test.Ns;

            [Marker]
            public partial class Data
            {
            }

            internal sealed class MarkerAttribute : System.Attribute
            {
            }
            """);

        var generated = result.FindGeneratedSource("Test_Ns_Data_Marker.g.cs");

        Assert.NotNull(generated);
        Assert.Contains("partial class Data", generated, StringComparison.Ordinal);
    }

    // Emits one file per [Marker] type through HintNameBuilder and the AddSource extension —
    // the shape every generator in the ecosystem uses.
    internal sealed class BuilderOutputGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Test.Ns.MarkerAttribute",
                    static (_, _) => true,
                    static (syntaxContext, _) => (
                        Namespace: syntaxContext.TargetSymbol.ContainingNamespace.ToDisplayString(),
                        syntaxContext.TargetSymbol.Name));

            context.RegisterSourceOutput(provider, static (sourceContext, model) =>
            {
                var builder = new SourceBuilder();
                builder.AutoGenerated();
                builder.Namespace(model.Namespace);
                builder.NewLine();
                builder.AppendLine($"public partial class {model.Name}");
                builder.BeginScope();
                builder.EndScope();

                sourceContext.AddSource(HintNameBuilder.Build(model.Namespace, model.Name, "Marker"), builder);
            });
        }
    }
}
